In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [2]:
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

In [3]:
lr=linear_model.LogisticRegression()
dt=DecisionTreeClassifier()
bn=BernoulliNB()

In [4]:
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)

In [5]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [6]:
df2=df.sample(frac=1)

In [7]:
df2.shape

(569, 31)

In [8]:
hold_on_data=df2.iloc[0:285,:]

In [9]:
hold_on_data.shape

(285, 31)

In [10]:
hold_on_data

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
261        17.35         23.06          111.00      933.1          0.08662   
235        14.03         21.25           89.79      603.4          0.09070   
457        13.21         25.25           84.10      537.9          0.08791   
317        18.22         18.87          118.70     1027.0          0.09746   
85         18.46         18.52          121.10     1075.0          0.09874   
..           ...           ...             ...        ...              ...   
373        20.64         17.35          134.80     1335.0          0.09446   
70         18.94         21.31          123.60     1130.0          0.09009   
560        14.05         27.15           91.38      600.4          0.09929   
432        20.18         19.54          133.80     1250.0          0.11330   
342        11.06         14.96           71.49      373.9          0.10330   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
261           0.06290         0.02891              0.02837         0.1564   
235           0.06945         0.01462              0.01896         0.1517   
457           0.05205         0.02772              0.02068         0.1619   
317           0.11170         0.11300              0.07950         0.1807   
85            0.10530         0.13350              0.08795         0.2132   
..                ...             ...                  ...            ...   
373           0.10760         0.15270              0.08941         0.1571   
70            0.10290         0.10800              0.07951         0.1582   
560           0.11260         0.04462              0.04304         0.1537   
432           0.14890         0.21330              0.12590         0.1724   
342           0.09097         0.05397              0.03341         0.1776   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
261                 0.05307  ...          31.47           128.20      1218.0   
235                 0.05835  ...          30.28            98.27       715.5   
457                 0.05584  ...          34.23            91.29       632.9   
317                 0.05664  ...          25.00           140.90      1485.0   
85                  0.06022  ...          27.68           152.20      1603.0   
..                      ...  ...            ...              ...         ...   
373                 0.05478  ...          23.17           166.80      1946.0   
70                  0.05461  ...          26.58           165.90      1866.0   
560                 0.06171  ...          33.17           100.20       706.7   
432                 0.06053  ...          25.07           146.00      1479.0   
342                 0.06907  ...          19.90            79.76       440.0   

     worst smoothness  worst compactness  worst concavity  \
261            0.1240             0.1486          0.12110   
235            0.1287             0.1513          0.06231   
457            0.1289             0.1063          0.13900   
317            0.1434             0.2763          0.38530   
85             0.1398             0.2089          0.31570   
..                ...                ...              ...   
373            0.1562             0.3055          0.41590   
70             0.1193             0.2336          0.26870   
560            0.1241             0.2264          0.13260   
432            0.1665             0.2942          0.53080   
342            0.1418             0.2210          0.22990   

     worst concave points  worst symmetry  worst fractal dimension  target  
261               0.08235          0.2452                  0.06515       0  
235               0.07963          0.2226                  0.07617       1  
457               0.06005          0.2444                  0.06788       1  
317               0.17760          0.2812                  0.08198       0  
85                0.16420          0.3695                  0.085

In [11]:
df1=df2.iloc[286:569,:]

In [12]:
y=df1.iloc[:,-1]

In [13]:
y

326    1
147    1
507    1
80     1
561    1
      ..
536    0
406    1
321    0
298    1
272    0
Name: target, Length: 283, dtype: int64

In [14]:
X=df1.iloc[:,:-1]

In [15]:
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
326        14.11         12.88           90.03      616.5          0.09309   
147        14.95         18.77           97.84      689.5          0.08138   
507        11.06         17.12           71.25      366.5          0.11940   
80         11.45         20.97           73.81      401.5          0.11020   
561        11.20         29.37           70.67      386.0          0.07449   
..           ...           ...             ...        ...              ...   
536        14.27         22.55           93.77      629.8          0.10380   
406        16.14         14.86          104.30      800.0          0.09495   
321        20.16         19.66          131.10     1274.0          0.08020   
298        14.26         18.17           91.22      633.1          0.06576   
272        21.75         20.99          147.30     1491.0          0.09401   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
326           0.05306         0.01765              0.02733         0.1373   
147           0.11670         0.09050              0.03562         0.1744   
507           0.10710         0.04063              0.04268         0.1954   
80            0.09362         0.04591              0.02233         0.1842   
561           0.03558         0.00000              0.00000         0.1060   
..                ...             ...                  ...            ...   
536           0.11540         0.14630              0.06139         0.1926   
406           0.08501         0.05500              0.04528         0.1735   
321           0.08564         0.11550              0.07726         0.1928   
298           0.05220         0.02475              0.01374         0.1635   
272           0.19610         0.21950              0.10880         0.1721   

     mean fractal dimension  ...  worst radius  worst texture  \
326                 0.05700  ...         15.53          18.00   
147                 0.06493  ...         16.25          25.47   
507                 0.07976  ...         11.69          20.74   
80                  0.07005  ...         13.11          32.16   
561                 0.05502  ...         11.92          38.30   
..                      ...  ...           ...            ...   
536                 0.05982  ...         15.29          34.27   
406                 0.05875  ...         17.71          19.58   
321                 0.05096  ...         23.06          23.03   
298                 0.05586  ...         16.22          25.26   
272                 0.06194  ...         28.19          28.18   

     worst perimeter  worst area  worst smoothness  worst compactness  \
326            98.40       749.9           0.12810            0.11090   
147           107.10       809.7           0.09970            0.25210   
507            76.08       411.1           0.16620            0.20310   
80             84.53       525.1           0.15570            0.16760   
561            75.19       439.6           0.09267            0.05494   
..               ...         ...               ...                ...   
536           104.30       728.3           0.13800            0.27330   
406           115.90       947.9           0.12060            0.17220   
321           150.20      1657.0           0.10540            0.15370   
298           105.80       819.7           0.09445            0.21670   
272           195.90      2384.0           0.12720            0.47250   

     worst concavity  worst concave points  worst symmetry  \
326          0.05307               0.05890          0.2100   
147          0.25000               0.08405          0.2852   
507          0.12560               0.09514          0.2780   
80           0.17550               0.06127          0.2762   
561          0.00000               0.00000          0.1566   
..               ...                   ...             ...   
536          0.42340               0.13620         

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [17]:
X

array([[ 0.05246611, -1.44839586, -0.02587438, ..., -0.77446122,
        -1.33490087, -0.71752717],
       [ 0.29047242, -0.08309568,  0.29389932, ..., -0.40385477,
        -0.0760071 ,  0.4258388 ],
       [-0.81172346, -0.46556517, -0.79480524, ..., -0.24043428,
        -0.19653948,  1.74432452],
       ...,
       [ 1.76667823,  0.12320604,  1.65570126, ...,  0.45745523,
         0.26382726, -1.33339174],
       [ 0.09496724, -0.2221755 ,  0.02284914, ..., -0.5327934 ,
        -0.43760425, -0.39995526],
       [ 2.21719017,  0.43149963,  2.31899625, ...,  1.07046628,
        -0.10781425,  0.23304641]])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [19]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
bn.fit(X_train,y_train)

BernoulliNB()

In [20]:
h_X=hold_on_data.iloc[:,:-1]
h_y=hold_on_data.iloc[:,-1]

In [21]:
h_X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
261        17.35         23.06          111.00      933.1          0.08662   
235        14.03         21.25           89.79      603.4          0.09070   
457        13.21         25.25           84.10      537.9          0.08791   
317        18.22         18.87          118.70     1027.0          0.09746   
85         18.46         18.52          121.10     1075.0          0.09874   
..           ...           ...             ...        ...              ...   
373        20.64         17.35          134.80     1335.0          0.09446   
70         18.94         21.31          123.60     1130.0          0.09009   
560        14.05         27.15           91.38      600.4          0.09929   
432        20.18         19.54          133.80     1250.0          0.11330   
342        11.06         14.96           71.49      373.9          0.10330   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
261           0.06290         0.02891              0.02837         0.1564   
235           0.06945         0.01462              0.01896         0.1517   
457           0.05205         0.02772              0.02068         0.1619   
317           0.11170         0.11300              0.07950         0.1807   
85            0.10530         0.13350              0.08795         0.2132   
..                ...             ...                  ...            ...   
373           0.10760         0.15270              0.08941         0.1571   
70            0.10290         0.10800              0.07951         0.1582   
560           0.11260         0.04462              0.04304         0.1537   
432           0.14890         0.21330              0.12590         0.1724   
342           0.09097         0.05397              0.03341         0.1776   

     mean fractal dimension  ...  worst radius  worst texture  \
261                 0.05307  ...         19.85          31.47   
235                 0.05835  ...         15.33          30.28   
457                 0.05584  ...         14.35          34.23   
317                 0.05664  ...         21.84          25.00   
85                  0.06022  ...         22.93          27.68   
..                      ...  ...           ...            ...   
373                 0.05478  ...         25.37          23.17   
70                  0.05461  ...         24.86          26.58   
560                 0.06171  ...         15.30          33.17   
432                 0.06053  ...         22.03          25.07   
342                 0.06907  ...         11.92          19.90   

     worst perimeter  worst area  worst smoothness  worst compactness  \
261           128.20      1218.0            0.1240             0.1486   
235            98.27       715.5            0.1287             0.1513   
457            91.29       632.9            0.1289             0.1063   
317           140.90      1485.0            0.1434             0.2763   
85            152.20      1603.0            0.1398             0.2089   
..               ...         ...               ...                ...   
373           166.80      1946.0            0.1562             0.3055   
70            165.90      1866.0            0.1193             0.2336   
560           100.20       706.7            0.1241             0.2264   
432           146.00      1479.0            0.1665             0.2942   
342            79.76       440.0            0.1418             0.2210   

     worst concavity  worst concave points  worst symmetry  \
261          0.12110               0.08235          0.2452   
235          0.06231               0.07963          0.2226   
457          0.13900               0.06005          0.2444   
317          0.38530               0.17760          0.2812   
85           0.31570               0.16420          0.3695   
..               ...                   ...             ...   
373          0.41590               0.21120         

In [22]:
h_X=sc.fit_transform(h_X)

In [23]:
x1=lr.predict(h_X)
x2=dt.predict(h_X)
x3=bn.predict(h_X)

In [24]:
x1

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1])

In [25]:
x2

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1])

In [26]:
x3

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1])

In [27]:
df3=pd.DataFrame(data=[x1,x2,x3])

In [28]:
df4=df3.T

In [29]:
df4

0  1  2
0    0  0  1
1    1  1  1
2    1  1  1
3    0  0  0
4    0  0  0
..  .. .. ..
280  0  0  0
281  0  0  0
282  1  1  1
283  0  0  0
284  1  1  1

[285 rows x 3 columns]

In [30]:
lr2=LogisticRegression()

In [31]:
df4_X=df4.iloc[:,:]
df4_Y=h_y

In [32]:
df4_X

0  1  2
0    0  0  1
1    1  1  1
2    1  1  1
3    0  0  0
4    0  0  0
..  .. .. ..
280  0  0  0
281  0  0  0
282  1  1  1
283  0  0  0
284  1  1  1

[285 rows x 3 columns]

In [33]:
df4_Y

261    0
235    1
457    1
317    0
85     0
      ..
373    0
70     0
560    1
432    0
342    1
Name: target, Length: 285, dtype: int64

In [34]:
lr2.fit(df4_X,df4_Y)

LogisticRegression()

In [35]:
X_test=sc.fit_transform(X_test)

In [36]:
X_test

array([[-0.5628261 ,  0.05543421, -0.58549172, ..., -0.55515922,
         0.78939562, -0.67529298],
       [ 0.12617161, -0.71276333,  0.06477556, ..., -0.26649783,
        -1.2209721 , -0.87625711],
       [ 0.10412368, -1.33179629,  0.0935874 , ...,  0.02732909,
        -1.17973379, -0.54152238],
       ...,
       [-0.63448186,  0.35624942, -0.57028547, ..., -0.09968192,
         0.1862853 , -0.69193725],
       [ 0.45689051,  3.00640662,  0.61740271, ...,  2.06467085,
         2.13479555,  3.67317621],
       [-0.84669316,  0.02062914, -0.8447983 , ..., -0.52295069,
        -1.08866585, -0.17843075]])

In [37]:
x4=lr.predict(X_test)
x5=dt.predict(X_test)
x6=bn.predict(X_test)

In [38]:
df5=pd.DataFrame(data=[x4,x5,x6])

In [39]:
df6=df5.T

In [40]:
df6

0  1  2
0   1  1  1
1   1  1  1
2   1  1  0
3   1  1  1
4   1  1  1
.. .. .. ..
89  1  1  1
90  1  1  1
91  1  1  1
92  0  0  0
93  1  1  1

[94 rows x 3 columns]

In [41]:
df6_X=df6.iloc[:,:]


In [42]:
final=lr2.predict(df6_X)

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
accuracy_score(y_test, final)


0.9574468085106383

In [45]:
precision = precision_score(y_test, final, average=None)
recall = recall_score(y_test, final, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.87096774 1.        ]
recall: [1.         0.94029851]


In [46]:
from sklearn.ensemble import StackingClassifier

In [47]:
df_X=df.iloc[:,:-1]
df_y=df.iloc[:,-1]

In [48]:
df_X=sc.fit_transform(df_X)

In [49]:
df_X.shape

(569, 30)

In [50]:
df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df_X, df_y, test_size=0.33)

In [51]:
estimators=[('lr',LogisticRegression()),('dt',DecisionTreeClassifier()),('bn',BernoulliNB())]

In [52]:
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

In [53]:
clf.fit(df_X_train,df_y_train)

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('dt', DecisionTreeClassifier()),
                               ('bn', BernoulliNB())],
                   final_estimator=LogisticRegression())

In [54]:
final1=clf.predict(df_X_test)

In [55]:
accuracy_score(df_y_test, final1)

0.9627659574468085

In [56]:
precision = precision_score(df_y_test, final1, average=None)
recall = recall_score(df_y_test, final1, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.94827586 0.96923077]
recall: [0.93220339 0.97674419]
