# 1_NB_Classifier_Weather

In [31]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [32]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

In [33]:
#create labelEncoder
le = preprocessing.LabelEncoder()

#converting string labels into numbers
weather_encoded = le.fit_transform(weather)
print("Weather :",weather_encoded)

temp_encoded = le.fit_transform(temp)
print("Temp :",temp_encoded)

label = le.fit_transform(play)
print("Play :",label)

Weather : [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp : [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play : [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [34]:
#combining weather and temp into single listof tuple
features = tuple(zip(weather_encoded,temp_encoded))
print("Features :",features)

Features : ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [35]:
#create classifier
model = MultinomialNB()

#train the model using the training sets
model.fit(features,label)

MultinomialNB()

In [36]:

#predict output
predicted = model.predict([[0,1]]) #0:overcast,1:Hot
print("Predicted Value:",predicted)

predicted= model.predict([[2,2]]) #2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]
Predicted Value: [1]


# 2_NB_Classifier_Iris

In [37]:
import numpy as np
from sklearn import datasets

#Load dataset
iris = datasets.load_iris()

In [38]:
print("Features :",iris.feature_names)
print("\nLabels :",iris.target_names)
print("\nData Shape: ",iris.data.shape)
print("\nData: ",iris.data)
print("\nTarget Shape: ",iris.target.shape)
print("\nTarget: ",iris.target)
print("\nData Type: ",type(iris.data))

newdata = iris.data[50:,:]
newtarget = iris.target[50:]

print("\nNew Data Shape: ",newdata.shape)
print("\nNew Target Shape: ",newtarget.shape)

Features : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Labels : ['setosa' 'versicolor' 'virginica']

Data Shape:  (150, 4)

Data:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.

In [39]:
from sklearn.model_selection import train_test_split

data_train,data_test,target_train,target_test = train_test_split(newdata,newtarget,test_size=0.30,random_state=53)

In [40]:
gnb = GaussianNB()
gnb.fit(data_train,target_train)
target_pred = gnb.predict(data_test)

In [41]:
from sklearn import metrics
print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))

Accuracy:  0.9333333333333333


In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test,target_pred)

array([[12,  1],
       [ 1, 16]])

In [43]:
from sklearn.metrics import precision_score,recall_score
precision = precision_score(target_test,target_pred)
print('pricision: {}'.format(precision))
recall = recall_score(target_test,target_pred)
print('recall: {}'.format(recall))

pricision: 0.9230769230769231
recall: 0.9230769230769231


# 3_NB_Classifier_Iris

# Task - 1

In [44]:
import pandas as pd
import numpy as np
import io
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.naive_bayes import GaussianNB,MultinomialNB


In [45]:
# from google.colab import files
# uploaded = files.upload()
# datasets = pd.read_csv(io.BytesIO(uploaded['Dataset2.csv']))
datasets = pd.read_csv("Dataset2.csv")

In [46]:
datasets

Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N

In [47]:
le = LabelEncoder()
X=datasets.iloc[:,:-1].values
Y=datasets.iloc[:,-1].values

In [48]:
outlook_encoded=le.fit_transform(X[:,0])

In [49]:
outlook_encoded

array([1, 1, 0, 2, 2, 2, 0, 1, 1, 2, 1, 0, 0, 2])

In [50]:
temp_encoded=le.fit_transform(X[:,1])

In [51]:
temp_encoded

array([1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2])

In [52]:
Wind_encoded=le.fit_transform(X[:,2])

In [53]:
Wind_encoded

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1])

In [54]:
humidity_encoded=le.fit_transform(X[:,3])

In [55]:
humidity_encoded

array([2, 0, 2, 2, 2, 1, 2, 2, 1, 0, 0, 1, 2, 2])

In [56]:
Y

array(['N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N'], dtype=object)

In [57]:
features= np.array(list(zip(outlook_encoded,temp_encoded,Wind_encoded,humidity_encoded)),dtype=object)

print("Features: ", features)
print("Target: ",Y)

Features:  [[1 1 0 2]
 [1 1 1 0]
 [0 1 0 2]
 [2 2 0 2]
 [2 2 0 2]
 [2 2 1 1]
 [0 0 1 2]
 [1 0 0 2]
 [1 0 0 1]
 [2 2 0 0]
 [1 2 1 0]
 [0 2 1 1]
 [0 1 0 2]
 [2 2 1 2]]
Target:  ['N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N']


In [58]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(features,
Y, test_size = 0.1, random_state = 53)
print(data_train.shape,target_train.shape)

(12, 4) (12,)


In [59]:
data_test

array([[2, 2, 0, 2],
       [0, 1, 0, 2]], dtype=object)

In [60]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [61]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.5


In [62]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0. 1.]
recall: [0.  0.5]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Nor-
mal’, and Wind = ’False’?**bold text**

In [63]:
pre=[1,2,2,0]
np.array(pre).reshape(1,-1)

array([[1, 2, 2, 0]])

In [64]:
gnb.predict(np.array(pre).reshape(1,-1))

array(['Y'], dtype='<U1')

In [65]:
gnb.predict_proba(np.array(pre).reshape(1,-1))

array([[0.32357918, 0.67642082]])

(2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
and Wind = ’True’?**bold text**

In [66]:
pre=[2,0,0,1]
np.array(pre).reshape(1,-1)

array([[2, 0, 0, 1]])

In [67]:
gnb.predict(np.array(pre).reshape(1,-1))

array(['Y'], dtype='<U1')

In [68]:
gnb.predict_proba(np.array(pre).reshape(1,-1))

array([[0.04256893, 0.95743107]])

# Task:2

In [69]:
import sklearn
from sklearn import datasets
digit_data = sklearn.datasets.load_digits();
features = digit_data.feature_names
targets = digit_data.target_names
print(digit_data.feature_names)

['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7']


In [70]:
df=pd.DataFrame(digit_data.data, columns=digit_data.feature_names)
df["target"]=pd.Series(digit_data.target)

In [71]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [72]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(digit_data.data,
digit_data.target, test_size = 0.35, random_state = 53)
print(data_test)
data_train

[[ 0.  0.  4. ...  0.  0.  0.]
 [ 0.  0.  8. ...  4.  0.  0.]
 [ 0.  2. 13. ...  0.  0.  0.]
 ...
 [ 0.  0.  2. ...  5.  0.  0.]
 [ 0.  0. 15. ...  0.  0.  0.]
 [ 0.  0.  7. ...  0.  0.  0.]]


array([[ 0.,  1., 12., ..., 12.,  7.,  0.],
       [ 0.,  0.,  7., ...,  5.,  0.,  0.],
       [ 0.,  0.,  7., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  1., ..., 12.,  1.,  0.],
       [ 0.,  0.,  5., ..., 14.,  3.,  0.],
       [ 0.,  0., 11., ...,  0.,  0.,  0.]])

In [79]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)
target_pred

array([7, 5, 5, 5, 9, 2, 0, 9, 2, 9, 2, 1, 8, 5, 1, 9, 3, 1, 1, 6, 6, 0,
       8, 7, 0, 7, 5, 4, 8, 5, 0, 1, 6, 7, 4, 7, 7, 2, 7, 2, 3, 8, 5, 5,
       0, 9, 5, 8, 1, 1, 7, 5, 8, 5, 5, 2, 6, 8, 3, 2, 8, 7, 2, 3, 3, 5,
       8, 0, 5, 4, 5, 4, 2, 7, 8, 2, 6, 1, 8, 5, 5, 6, 7, 8, 2, 5, 4, 5,
       2, 7, 7, 8, 5, 1, 5, 6, 7, 3, 0, 8, 5, 5, 7, 1, 1, 8, 8, 1, 4, 7,
       6, 2, 6, 3, 1, 5, 8, 0, 5, 0, 8, 8, 4, 2, 2, 0, 4, 5, 3, 8, 9, 8,
       6, 6, 2, 1, 3, 1, 0, 0, 4, 9, 0, 4, 0, 2, 7, 4, 1, 1, 7, 7, 6, 8,
       6, 0, 4, 7, 0, 1, 2, 1, 4, 5, 8, 5, 7, 3, 9, 6, 3, 2, 8, 3, 8, 8,
       4, 8, 2, 4, 3, 7, 8, 4, 4, 8, 6, 5, 3, 7, 8, 4, 8, 9, 4, 4, 5, 6,
       9, 1, 8, 6, 7, 4, 4, 7, 8, 3, 1, 1, 5, 6, 2, 7, 3, 6, 2, 1, 1, 9,
       4, 0, 3, 7, 3, 7, 0, 8, 9, 8, 2, 8, 9, 2, 8, 5, 9, 1, 6, 5, 2, 0,
       7, 7, 6, 8, 7, 6, 9, 1, 7, 4, 4, 3, 5, 4, 6, 6, 8, 7, 7, 8, 2, 9,
       8, 0, 8, 8, 5, 4, 6, 1, 9, 7, 3, 5, 8, 8, 8, 0, 8, 7, 6, 4, 4, 6,
       2, 1, 3, 1, 4, 1, 0, 9, 1, 7, 6, 7, 6, 6, 2,

In [74]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.8600953895071543


In [75]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[57,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 46,  1,  0,  0,  0,  2,  2,  4,  2],
       [ 0,  1, 55,  0,  0,  0,  1,  0, 11,  0],
       [ 0,  1,  1, 39,  0,  2,  0,  0, 15,  0],
       [ 1,  1,  0,  0, 67,  1,  0,  6,  3,  0],
       [ 0,  0,  0,  0,  1, 66,  1,  2,  1,  0],
       [ 0,  0,  0,  0,  0,  0, 63,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0, 59,  1,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  4, 51,  0],
       [ 0,  4,  1,  0,  1,  1,  0,  5,  8, 38]])

In [76]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.98275862 0.83636364 0.94827586 1.         0.97101449 0.92957746
 0.94029851 0.75641026 0.54255319 0.95      ]
recall: [1.         0.80701754 0.80882353 0.67241379 0.84810127 0.92957746
 1.         0.96721311 0.89473684 0.65517241]
